### ISSUE TITLE
Toggling SM5 and SM6 modes cause materials to get the skeletal mesh flag

### ISSUE THREAD

**Issue by IntXThOrn** [Cesio137/EngineUserSettings-Documentation#2]
![image](https://github.com/Cesio137/EngineUserSettings-Documentation/assets/9694030/801cf675-b6bc-46b8-ba8c-6336fc6356f2)

**Comment by nathancmiguel** [comment]
Could you give me some details such as the material node that is having the problem and if you selected the shader 5 and 6 in the project settings?
