### ISSUE TITLE
(Get Shadow Method) Doesnt work i have the Fix see description

### ISSUE THREAD

**Issue by Dante1243** [Cesio137/EngineUserSettings-Documentation#3]
In the (Get Shadow Method) function your using (Get Console Varable Int Value (r.ReflectionMethod)) this doent work because your getting the reflection method and not the shadow map method the value you need to get is (Get Console Varable Int Value (r.Shadow.Virtual.Enable))
Please mark this issue as closed when fixed.
Thanks.
![Screenshot 2023-11-14 223315](https://github.com/Cesio137/EngineUserSettings-Documentation/assets/87241107/788842cc-f29c-41b7-b6d8-7ca84b856975)

**Comment by nathancmiguel** [comment]
I updateded the plugin with fixes.

**Comment by BITRABBBIT** [comment]
> Я обновил плагин исправлениями.

Hi. I noticed that this has not been fixed for 5.1, is it worth it for 5.1 users to make these changes as well?

**Comment by Dante1243** [comment]
> > Я обновил плагин исправлениями.
> 
> Hi. I noticed that this has not been fixed for 5.1, is it worth it for 5.1 users to make these changes as well?

Yes otherwise the (Get Shadow Method) function won't work.

**Comment by nathancmiguel** [comment]
@BITRABBBIT @Dante1243 

![image](https://github.com/Cesio137/EngineUserSettings-Documentation/assets/29849613/c7db26c8-e6b0-47d5-be02-24c3d82ac4c3)

**Comment by Dante1243** [comment]
> @BITRABBBIT @Dante1243 
> 
> ![image](https://github.com/Cesio137/EngineUserSettings-Documentation/assets/29849613/c7db26c8-e6b0-47d5-be02-24c3d82ac4c3)
> 

Thanks for pushing the update do you have a change log available.

**Comment by nathancmiguel** [comment]
@Dante1243 Noup, I only fixed the Get Shadow Method node.
