### ISSUE TITLE
(Set prefered RHI) Issue

### ISSUE THREAD

**Issue by Dante1243** [Cesio137/EngineUserSettings-Documentation#4]
I'm using Unreal 5.2.1 Source build and the (Set prefered RHI) function doesn't work I've had to use your old RHI switcher plugin to be able to switch the RHI.

**Comment by nathancmiguel** [comment]
> I'm using Unreal 5.2.1 Source build and the (Set prefered RHI) function doesn't work I've had to use your old RHI switcher plugin to be able to switch the RHI.

@Dante1243 

I have some questions before, because this node is suppose to work after you restart your game. 

1. Did you enable support for other RHI in Project settings?

2. Did this problem occur using the plugin in the Engine or after you compile in shipping mode?

**Comment by Dante1243** [comment]
1. Yes I have Direct X 11/12 enabled in project settings
2. This issue happens in a packaged build

**Comment by Dante1243** [comment]
@Cesio137

**Comment by nathancmiguel** [comment]
@Dante1243 I downloaded the plugin and compiled the project using Unreal engine 5.2 in shipping mode. As you can see in the video below, there is no issue in the "Set Preferred RHI" node.

![image](https://github.com/Cesio137/EngineUserSettings-Documentation/assets/29849613/5a1d10c4-96db-480d-ad76-23fa11369517)


https://github.com/Cesio137/EngineUserSettings-Documentation/assets/29849613/3c8782e8-9d2a-43cf-a956-e96ca81fd6a8

**Comment by Dante1243** [comment]
Does the project configuration have to be in shipping

**Comment by nathancmiguel** [comment]
> Does the project configuration have to be in shipping

Yep, I did this to avoid conflicts to other. config files

**Comment by Dante1243** [comment]
> > Does the project configuration have to be in shipping
> 
> Yep, I did this to avoid conflicts to other. config files

Oh okay I dident know please mention this in the documentation
Thanks
